name: GymApp
options:
  bundleIdPrefix: com.gymapp
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only

targets:
  GymApp:
    type: application
    platform: iOS
    sources:
      - GymApp
    resources:
      - GymApp/Resources
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark
        GENERATE_INFOPLIST_FILE: true
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.1.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.gymapp.GymApp
        PRODUCT_NAME: "Gym App"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_STRICT_CONCURRENCY: complete

  GymAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - GymAppTests
    dependencies:
      - target: GymApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.gymapp.GymAppTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/GymApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/GymApp"
        BUNDLE_LOADER: "$(TEST_HOST)"

  GymAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - GymAppUITests
    dependencies:
      - target: GymApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.gymapp.GymAppUITests
        TEST_TARGET_NAME: GymApp

schemes:
  GymApp:
    build:
      targets:
        GymApp: all
        GymAppTests: [test]
        GymAppUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - GymAppTests
        - GymAppUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
