name: Pulse
options:
  bundleIdPrefix: com.pulse
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only

targets:
  Pulse:
    type: application
    platform: iOS
    sources:
      - Pulse
    resources:
      - Pulse/Resources
    entitlements:
      path: Pulse/Pulse.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark
        INFOPLIST_KEY_NSHealthShareUsageDescription: "Pulse reads your body weight from Apple Health to display in your profile."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "Pulse saves your completed workouts to Apple Health."
        GENERATE_INFOPLIST_FILE: true
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "0.12.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.pulse.Pulse
        PRODUCT_NAME: "Pulse"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_STRICT_CONCURRENCY: complete
    attributes:
      SystemCapabilities:
        com.apple.HealthKit:
          enabled: true

  PulseTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PulseTests
    dependencies:
      - target: Pulse
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.pulse.PulseTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Pulse.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Pulse"
        BUNDLE_LOADER: "$(TEST_HOST)"

  PulseUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PulseUITests
    dependencies:
      - target: Pulse
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.pulse.PulseUITests
        TEST_TARGET_NAME: Pulse

schemes:
  Pulse:
    build:
      targets:
        Pulse: all
        PulseTests: [test]
        PulseUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - PulseTests
        - PulseUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
